# Generated by Django 3.0.7 on 2020-06-20 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20200620_1220'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('parent__id', 'position'), 'verbose_name': 'دسته بندی', 'verbose_name_plural': 'دستع بندی ها'},
        ),
        migrations.AlterField(
            model_name='category',
            name='position',
            field=models.IntegerField(default=0, verbose_name=' پوزیشن'),
        ),
    ]
